export const metadata = {
    title: 'about',
    description: 'Generated by create next app',
}

export default function about() {
    return (
        <div className="mt-[200px]">
            <h1 className="text-center font-bold text-3xl">about page</h1>

        </div>
    )
}