export const metadata = {
    title: 'contact',
    description: 'Generated by create next app',
}

export default function countact() {
    return (
        <div className="mt-[200px]">
            <h1 className="text-center font-bold text-3xl">countact page</h1>
        </div>
    )
}